refactor: get binaryMessenger from FlutterPluginRegistrar instead of FlutterViewController
Fix the error when applying UIScene lifecycle support:
expresspay_sdk/ExpresspaySdkPlugin.swift:22: Fatal error: Unexpectedly found nil while unwrapping an Optional value